[package]
name = "plonky2_poseidon_standalone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2_field = { path = "../field" }
unroll = "0.1.5"